export { default as Navbar } from "./navbar/Navbar";
export { default as Hero } from "./hero/Hero";
export { default as Footer } from "./footer/Footer";
export { default as WhyDolfinSection } from "./section/WhyDolfin";
export { default as FeaturesSection } from "./section/FeaturesSection";
export { default as HowItWorksSection } from "./section/HowWorksSection";
export { default as TrustSection } from "./section/TrustSection";
export { default as BenefitsSection } from "./section/BenefitsSection";
export { default as SupportSection } from "./section/SupportSection";
